### ISSUE TITLE
nes emulater for flipper ? 

### ISSUE THREAD

**Issue by jayuserdrugabuser** [Spooks4576/ghost_esp_app#23]
how do i compile this to work on flipper got it to work with sys2 do i use ufbt and hope for the best ? or is it not really supported for flipper

**Comment by jaylikesbunda** [comment]
what exactly does this have to do with nes emulation on the flipper which doesn't exist btw
the compiled app versions are in releases

**Comment by jayuserdrugabuser** [comment]
nothing at all i just didnt see a quicker way to ask you a question sorry
for that but i saw your repo said nes4flipper i compiled and built it for
windows on msys2 but how dose one go about adding it 4 flipper will ufbt
compile it as a frap ? or am i way off on this idea ? sorry agian just dumb
an trying to lean this world ...for free lol

**Comment by jayuserdrugabuser** [comment]
also do i need flash my esp32s2 for flipper with murader to run ghost fap
cuz i dont see anythin but the fap firmware ?
